Assorted changes
neatnik/omg.lol pull request #464
Opened 2023-01-04 21:44 UTC by Zacatero

Same as my old PR, minus the Discord stuff

2023-01-04 22:11 UTC, lxjv approved these changes
looks good!

2023-01-06 20:10 UTC, Vukkyy requested changes

2023-01-06 20:10 UTC, Vukkyy commented on info/Profile & Web/profile-items.md
> +If you’d like to have a specific icon appear on a profile item, just use an icon tag, like this: `{cat}`. Put it at the end of the line, and when your profile is published, the tag will be removed an
```suggestion
If you’d like to have a specific icon appear on a profile item, just use an icon tag, like this: `{cat}`. Put it at the end of the line, and when your profile is published, the tag will be removed and the icon will be applied. You can use any icon in the [Font Awesome free set](https://fontawesome.com/search?m=free&o=r), as well as any of the [custom omg.lol icons](https://omgalol.cache.lol/profiles/icons/omg.lol-icons.html).
```
Maybe link to the omg.lol icon list? I don't know how accurate or stable this is, but I know it exists, so...

2023-01-06 21:54 UTC, merged

2023-01-06 21:54 UTC, lxjv commented
thanks @Zacatero and @Vukkyy !!