Remove references to Classic Editor
neatnik/omg.lol pull request #611
Opened 2023-02-25 05:33 UTC by plttn

2023-02-25 09:40 UTC, lxjv requested changes
can you remove any mentions to the editor being advanced as there is only one editor now? (ill go around and fix links after)

2023-02-26 09:20 UTC, Vukkyy commented on info/Profile & Web/classic-editor.md
> +We’re retiring our Classic Web Editor on January 31, 2023. [Read more here](https://omglol.news/2023/01/14/so-long-classic-web-editor).
It's already retired, so maybe this page should be removed/redirected?

(disclaimer: i am not a staff.lol)

2023-02-26 09:46 UTC, byemc commented
I vote for redirecting “/classic-editor” to “/editor” and renaming “/advanced-editor.md” to just “/editor.md"

~bye

> On 26 Feb 2023, at 09:21, Vukky ***@***.***> wrote:
> ﻿
> 
> 
> ***@***.**** commented on this pull request.
> 
> 
> In info/Profile & Web/classic-editor.md <https://github.com/neatnik/omg.lol/pull/611#discussion_r1118048746>:
> 
> > \ No newline at end of file
> +We’re retiring our Classic Web Editor on January 31, 2023. [Read more here](https://omglol.news/2023/01/14/so-long-classic-web-editor).
> 
> It's already retired, so maybe this page should be removed/redirected?
> 
> (disclaimer: i am not a staff.lol)
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/neatnik/omg.lol/pull/611#pullrequestreview-1314634086>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ASRSTDTAZ3WQPEB55XTWPDDWZMOALANCNFSM6AAAAAAVHUX6RQ>.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
>

2023-02-26 11:13 UTC, byemc approved these changes

2023-02-26 14:52 UTC, lxjv approved these changes
nice :D

2023-02-26 14:52 UTC, lxjv commented
> I vote for redirecting “/classic-editor” to “/editor” and renaming “/advanced-editor.md” to just “/editor.md" - @byemc 

me too, ill send a PR in

2023-02-26 14:52 UTC, merged